# Generated by Django 4.2.5 on 2023-09-21 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Seo Title', models.CharField(max_length=150)),
                ('Seo Description', models.TextField(max_length=500)),
                ('Seo Keywords', models.TextField(max_length=500)),
                ('Название', models.CharField(max_length=150)),
                ('Заголовок H1', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
