# Generated by Django 4.2.5 on 2023-09-21 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_alter_article_seo_keywords'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='slug',
            new_name='Символьный код',
        ),
    ]
