# Generated by Django 4.2.5 on 2023-09-21 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_rename_slug_article_символьный_код'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='Seo Description',
        ),
        migrations.RemoveField(
            model_name='article',
            name='Seo Keywords',
        ),
        migrations.RemoveField(
            model_name='article',
            name='Seo Title',
        ),
        migrations.RemoveField(
            model_name='article',
            name='Заголовок H1',
        ),
        migrations.RemoveField(
            model_name='article',
            name='Название',
        ),
        migrations.RemoveField(
            model_name='article',
            name='Символьный код',
        ),
        migrations.AddField(
            model_name='article',
            name='announce',
            field=models.TextField(default='', max_length=500, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.TextField(default='', max_length=10000, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='article',
            name='h1',
            field=models.CharField(default='', max_length=150, verbose_name='Заголовок H1'),
        ),
        migrations.AddField(
            model_name='article',
            name='name',
            field=models.CharField(default='', max_length=150, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='article',
            name='seo_description',
            field=models.TextField(default='', max_length=500, verbose_name='Seo Description'),
        ),
        migrations.AddField(
            model_name='article',
            name='seo_keywords',
            field=models.CharField(default='', max_length=100, verbose_name='Seo Keywords'),
        ),
        migrations.AddField(
            model_name='article',
            name='seo_title',
            field=models.CharField(default='', max_length=150, verbose_name='Seo Title'),
        ),
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='', unique=True, verbose_name='Символьный код'),
        ),
    ]
