# Generated by Django 4.2.5 on 2023-09-22 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0006_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='announce',
            field=models.TextField(blank=True, default='', max_length=500, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(blank=True, default='', max_length=10000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='article',
            name='h1',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Заголовок H1'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='seo_description',
            field=models.TextField(blank=True, default='', max_length=500, verbose_name='Seo Description'),
        ),
        migrations.AlterField(
            model_name='article',
            name='seo_keywords',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Seo Keywords'),
        ),
        migrations.AlterField(
            model_name='article',
            name='seo_title',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Seo Title'),
        ),
    ]
