# Generated by Django 4.2.5 on 2023-09-25 13:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0007_alter_article_announce_alter_article_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 9, 25, 13, 45, 33, 791086), verbose_name='Дата публикации'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='', max_length=100, unique=True, verbose_name='Символьный код'),
        ),
    ]
