# Generated by Django 4.2.5 on 2023-10-05 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shopapp', '0011_remove_order_client_remove_order_products_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=150, verbose_name='Имя')),
                ('last_name', models.CharField(default='', max_length=150, verbose_name='Фамилия')),
                ('password', models.CharField(default='', max_length=50, verbose_name='Пароль')),
                ('phone', models.CharField(default='', max_length=15, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.CharField(default='', max_length=300, verbose_name='Адрес')),
                ('date_registration', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
            ],
            options={
                'verbose_name': 'клиента',
                'verbose_name_plural': 'клиенты',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ordersapp.client', verbose_name='Пользователь')),
                ('products', models.ManyToManyField(to='shopapp.product', verbose_name='Товары')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
            },
        ),
    ]
