# Generated by Django 4.2.5 on 2023-09-21 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150, verbose_name='Название')),
                ('slug', models.SlugField(default='', unique=True, verbose_name='Символьный код')),
                ('h1', models.CharField(default='', max_length=150, verbose_name='Заголовок H1')),
                ('announce', models.TextField(default='', max_length=500, verbose_name='Краткое описание')),
                ('description', models.TextField(default='', max_length=10000, verbose_name='Описание')),
                ('seo_title', models.CharField(default='', max_length=150, verbose_name='Seo Title')),
                ('seo_description', models.TextField(default='', max_length=500, verbose_name='Seo Description')),
                ('seo_keywords', models.CharField(default='', max_length=100, verbose_name='Seo Keywords')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150, verbose_name='Название')),
                ('slug', models.SlugField(default='', unique=True, verbose_name='Символьный код')),
                ('h1', models.CharField(default='', max_length=150, verbose_name='Заголовок H1')),
                ('announce', models.TextField(default='', max_length=500, verbose_name='Краткое описание')),
                ('description', models.TextField(default='', max_length=10000, verbose_name='Описание')),
                ('seo_title', models.CharField(default='', max_length=150, verbose_name='Seo Title')),
                ('seo_description', models.TextField(default='', max_length=500, verbose_name='Seo Description')),
                ('seo_keywords', models.CharField(default='', max_length=100, verbose_name='Seo Keywords')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
