# Generated by Django 4.2.5 on 2023-10-05 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0008_product_characteristics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='characteristics',
            field=models.JSONField(default=dict, verbose_name='Характеристики'),
        ),
    ]
