# Generated by Django 4.2.5 on 2023-10-05 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0010_alter_product_characteristics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='client',
        ),
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
